name: Validate Code and Test Cases

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Restore
        run: dotnet restore
      - name: Run Semantic Kernel Validator
        run: dotnet run --project JiraAutomation-SK.csproj
